# The RAML API and autodiscovery
api:  
  group: "${restconnector.api.spec.group}"
  artifact: "${restconnector.api.spec.artifact}"
  version: "${restconnector.api.spec.version}"
  spec: "resource::${api.group}:${api.artifact}:${api.version}:raml:zip:api.raml"
  id: "0"

# For testing scenarios
test:
  basepath: "/api/contact"

messages:
  # Batch processing
  batch-primaryidentifier-notpresent: "There are some primary identifiers not present in the datastore"
  batch-backend-errorrecords: "Some records couldn't be processed in datastore"

batch:
  maxretries: "120"
  millisretry: "1000"

# Components to configure:
# - Salesforce connector
# - TLS connector
# - Mulesoft Gatekeeper (API Manager)
